ktor:
  application:
    modules:
      - com.connor.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "http://localhost/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  secret: "my-super-secret-key-change-me-in-production"
